### ISSUE TITLE
[UI] Define UI standards and tools

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/sensemaker-lite#11]
Desired outcome: we have a first pass on a document with UI standard and tools recommended for use by the team and external applet developers, available on Gitbook and visible on the website FAQ.

**Comment by adaburrows** [comment]
Current working draft: https://hackmd.io/@adaburrows/H1PREqwti

**Comment by adaburrows** [comment]
Now in GitBook: https://app.gitbook.com/o/-LsW4aUtl-OxRJ9EGgv3/s/rxnA9zMl0NbfQHBHQlSK/developer-preview-toolkit-0.0.1/applet-ux-guidelines-and-dev-tips
