### ISSUE TITLE
Fix code based on the code review by Damien for Developer Release

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/sensemaker-lite#17]
https://docs.google.com/document/d/1MtWiFyUpSkv2Vhy-WYdp7Mh57hqhHWtnbVYdgk8nBxc/edit?usp=sharing

*Actionable Items based on the google document above that are needed for the **developer release***

- [x] Create CRUD function for Range and modify other Entries to work with Range as an entry
- [x] rename ResourType to ResourceDef to align with HDK terminology
- [x] must_publish_dataset name should be changed to requires_validation. If it is true, DataSet must be committed to be retrievable in the validation The Objective Assesment must have the Data
- [x] update and delete shouldnt be allowed for dimension now. Updating dimension will be a problem for older assessments

**Comment by adaburrows** [comment]
Can this be closed?
