### ISSUE TITLE
`call_zome` timeout when registering Applet config

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/sensemaker-lite#31]
`this._sensemakerStore.registerApplet(...)` in [my `provider-app-test-harness.js`](https://github.com/neighbour-hoods/timetracking-applet/blob/476d696/ui/src/provider-app-test-harness.ts#L127) is timing out. I don't think there is anything that crazy in [my `appletConfig`](https://github.com/neighbour-hoods/timetracking-applet/blob/476d696e93c9b640c8df9bc9a7cf655b52a8f985/ui/src/appletConfig.ts)?

```
[Error] Error registering default applet configuration with Sensemaker store
Error: Timed out in 15000ms: call_zome
(anonymous function) — common.js:30
	(anonymous function) (b4941e87.js:2953:3350)
```

**Comment by pospi** [comment]
Propose https://github.com/neighbour-hoods/applet-template/issues/24 as a possible workaround for this issue.

**Comment by weswalla** [comment]
config looks pretty normal to me, not sure why it takes so long...
