### ISSUE TITLE
applet config mapping for Dashboard

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/sensemaker-lite#54]
currently we are not distinguishing applet configs and therefore there is no way to know which applet a set of primitives were defined in.

**Comment by weswalla** [comment]
two approaches:
- adapt matrix store to maintain this info
- store it completely in the SM

**Comment by weswalla** [comment]
if we pull the user given applet name (which is enforced to be unique per neighbourhood) we can feed that in to the applet registration.

**Comment by nick-stebbings** [comment]
@weswalla I have had a look but I have questions about new applet's config getting registered in the store.

I see the `defaultAppletConfig` getting registered in the `matrix-store.ts` file around line `1086` in `installWeGroup` method and also in `fetchMatrix`. I understand this was just for widget registration in the launcher. That is the only place in the matrix store where an applet config is registered.

If each applet is responsible for their own registration of config (so the code exists in the applet repo) then I don't see how we can feed in an applet instance id which has been generated in the matrix store.

Maybe if you have a clearer understanding of the solution you can point me specifically to the areas of code that need to change. cheers

**Comment by weswalla** [comment]
@nick-stebbings I'll take a look into this asap, and then hopefully by our coworking session on tuesday we can either fully complete it or at least clarify the path forward.
