### ISSUE TITLE
Support Multi-(multi-zome-)DNA Applets

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/sensemaker-lite#57]
Given the generic applet `webhapp` bundle architecture:
<img width="1067" alt="image" src="https://github.com/neighbour-hoods/sensemaker-lite/assets/39413655/9fb58453-2f57-4baf-9577-7c28138ab332">

We need the representation of an applet `happ` to sufficiently map resources to where they exists (path: `dna/zome/entry`). Since these dnas are bundled as a happ, we can reference them using their respective `roleId`s.

Such proposed changes would affect:
- applet config

the `resource_def` key in the object would change from a `ConfigResourceDef[]` to something more like:
```typescript
{
    [roleName: string]: {
        [zomeName: string]: ConfigResourceDef
    }
}
```

**Comment by pospi** [comment]
Related concerns building towards a generic future interface between the Sensemaker and Resource provider cells:

- #64
- #65
