### ISSUE TITLE
update sensemaker store to use holochain-open-dev/stores

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/sensemaker-lite#76]
https://www.npmjs.com/package/@holochain-open-dev/stores provides many more holochain specific utilities, we should update our sensemaker store to use this rather than svelte stores.

**Comment by weswalla** [comment]
https://github.com/holochain/syn/tree/645ce266c187a33d7879d702339ae263b8d7c45a/packages/store is a good example store.

**Comment by adaburrows** [comment]
There are better patterns. But I need some time to write them down or just implement them.
